## NUMPY
### WHY USE NUMPY INSTEAD?

#### In Python we have lists that serve the purpose of arrays, but they are slow to process.
#### NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
#### The array object in NumPy is called ndarray

## Starting with numpy

In [50]:
import numpy as np

In [51]:
#declaring an array
x = np.array([1, 2, 3])


In [52]:
x

array([1, 2, 3])

![](https://numpy.org/doc/stable/_images/np_array.png)

In [53]:
#create an array filled with 0’s
np.zeros(2) 

array([0., 0.])

In [54]:
#making a multi-dimensional array of zeros
np_array = np.zeros((2, 3))
np_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
#create an array filled with 1’s
np.ones(3)

array([1., 1., 1.])

In [56]:
#making a multi-dimensional array with ones
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
#create an array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [58]:
#creating an array that contains a range of evenly spaced intervals. To do this, you will specify 
#the first number, last number, and the step size.
np.arange(2, 9, 2)


array([2, 4, 6, 8])

In [59]:
#using linspace -> to create an array of eqidistant elements
#(first element, last element, no of elements)
np.linspace(1, 6, 5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [60]:
# sorting an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
#concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [62]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [64]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### How do you know the shape and size of an array?

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [65]:
arr1 = np.array([[[0, 1, 2, 3],
                  [4, 5, 6, 7]],

                 [[0, 1, 2, 3],
                  [4, 5, 6, 7]],

                 [[0 ,1 ,2, 3],
                  [4, 5, 6, 7]]])

In [66]:
arr1.ndim

3

In [67]:
arr1.size

24

In [68]:
arr1.shape

(3, 2, 4)

### Reshaping an array

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [69]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [70]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
a.shape

(6,)

In [72]:
b.shape

(3, 2)

In [73]:
#to flatten the array
shape = np.array([[3, 5, 17, 34, 45, 67],[6, 7, 19, 67, 95, 85]])
shape.ravel()

array([ 3,  5, 17, 34, 45, 67,  6,  7, 19, 67, 95, 85])

### Converting 1D array to 2D array(adding new axis)

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [74]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [75]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [76]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [77]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

### Indexing and Slicing


In [78]:
data = np.array([1, 2, 3])

In [79]:
data[1]

2

In [80]:
data[0:2]

array([1, 2])

In [81]:
data[1:]

array([2, 3])

In [82]:
data[-2:]

array([2, 3])

![](https://numpy.org/doc/stable/_images/np_indexing.png)

You can also use conditions to slice your array

In [83]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [84]:
print(a[a < 5])

[1 2 3 4]


In [85]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [87]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

You can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values.

In [88]:
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## OPERATIONS ON NUMPY ARRAYS

In [89]:
#vector addition or addition by element
a1 = np.array([2, 3, 5])
a2 = np.array([4, 7, 15])
a3 = a1+a2
a3

array([ 6, 10, 20])

In [90]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

![](https://numpy.org/doc/stable/_images/np_data_plus_ones.png)

In [91]:
ans1=data - ones
ans2=data * data
ans3=data / data

In [92]:
print(ans1)
print(ans2)
print(ans3)

[0 1]
[1 4]
[1. 1.]


![](https://numpy.org/doc/stable/_images/np_sub_mult_divide.png)

In [93]:
a = np.array([1, 2, 3, 4])
a.sum()

10

#### Broadcasting
There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [94]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

![](https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png)

In [95]:
max = data.max()
min = data.min()
sum = data.sum()

In [96]:
print(max)
print(min)
print(sum)

2.0
1.0
3.0


![](https://numpy.org/doc/stable/_images/np_aggregation.png)

## MATHEMATICAL FUNCTIONS OF NUMPY

In [97]:
np_sqrt = np.sqrt([2, 4, 8, 9])
np_sqrt

array([1.41421356, 2.        , 2.82842712, 3.        ])

In [98]:
from numpy import pi
np.cos(0)

1.0

In [99]:
np.cos(11/7)

-0.000632244591553242

In [100]:
np.floor([1.5, 2.8, 4.9])

array([1., 2., 4.])